### ISSUE TITLE
Advanced user settings - RPC override

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/davi-monorepo#10]
**User Story**
As a power user I want to be able to set my own RPC for each chain 

**Alternative Solutions**
Access from account modal, need to add the new advanced settings button which opens a new modal. 

We should then give an input to override the default RPC using a link provided by the user. We should check the availability of this link using a simple query before allowing the user to save. This option should then be saved specifically to the user's browser or local storage so it persists. 

An additional feature we can add here is the ability to override the app's decision to use the default data fetching option. In the case of guilds this should be a toggle between automatic and fallback (RPC only) where the user can choose to move from the default automatic logic to only using fallback data fetching. 
This choice should also be stored locally in browser.

**Comment by rulfo71** [comment]
Some comments we chat about this on the daily @rossneilson. 

- should we need some designs for this modal or just keep it simple like a text and label for each chain? 
- 1.5 won't work with this because we haven't implemented RPCs for it. 
- should we leave subgraph as a fallback for the case the RPC is not working? or maybe with a toggle as suggested @mprasanjith if the user doesn't want to use subgraph.

**Comment by rossneilson** [comment]
> * should we need some designs for this modal or just keep it simple like a text and label for each chain?

@borisblock3007 Would you be able to add something super simple for this in the current account modal?

> * 1.5 won't work with this because we haven't implemented RPCs for it.

Regardless we can keep the settings as the RPC setting will be used for all DAOs in the dapp

> * should we leave subgraph as a fallback for the case the RPC is not working? or maybe with a toggle as suggested @mprasanjith if the user doesn't want to use subgraph.

Not sure I understand this. The toggle mentioned in the issue should be "off" or "only use fallback (RPC)"

**Comment by borisblock3007** [comment]
here is a draft design for the custom RPC modal :)
![Custom RPC 2](https://user-images.githubusercontent.com/25454493/225579488-9bab340d-7f4e-435e-a79b-be27098ff2d5.png)

**Comment by rulfo71** [comment]
>Not sure I understand this. The toggle mentioned in the issue should be "off" or "only use fallback (RPC)"

By this i meant a toggle to turn it on and off in case you want to only use RPC, in case you just don't like subgraph because it's centralized (for now) or any reason

**Comment by rulfo71** [comment]
i made this comment on the PR but maybe this was the place to add it: 

I added decentralize mode:

<img width="475" alt="image" src="https://user-images.githubusercontent.com/5303411/227226100-8d4b7953-10b4-4952-8cc4-01d890f53c41.png">

i don't think this is the place we should add it, i just wanted to add the functionality until we have the designs.
Having it here is a bit confusing, first because this is a modal to change to customs RPCs which is not what we do with decentralize mode and also because i think it should be on a place where it is almost all the time visible so that the user can realize that a functionality is not working because of the decentralize mode is on.

@borisblock3007 @rossneilson let me know what you think
